document:
  name: Linee guida dell’indice dei domicili digitali delle pubbliche amministrazioni e dei gestori di pubblici servizi  
  description: Le presenti Linee Guida definiscono le informazioni che costituiscono l’Indice dei domicili digitali delle pubbliche amministrazioni e dei gestori di pubblici servizi (IPA) e le regole che dovranno essere seguite dagli Enti tenuti a pubblicare i propri riferimenti.
  tags:
    - linee guida
    - indice domicili digitali
